// Package crypto seals secrets at rest with AES-256-GCM.
//
// # Single key
//
// [Encryptor] seals with one key and stores ciphertext as nonce||sealed. The configured key is hashed to 32
// bytes, so any non-empty length is accepted. That hash is a plain unsalted SHA-256, so [New] is only suitable
// for keys that already have full entropy, such as randomly generated bytes. Derive a key from a human chosen
// password with a memory hard function like Argon2id or scrypt first.
//
// [Encryptor.EncryptWithAAD] additionally authenticates metadata stored in the clear next to the ciphertext.
//
// # Keyring
//
// [Keyring] holds several keys, so that a value written under an old key stays readable while new writes use
// the current one. It expands each configured key into an independent encryption and MAC subkey with
// HKDF-SHA256, which is what [MinKeyLen] exists to make safe, and derives HMAC digests for credentials that
// have to stay searchable.
//
// # Envelope format
//
// Every value [Keyring.Encrypt] produces is:
//
//	byte 0      format version, currently 1
//	byte 1      id of the key that sealed the value
//	byte 2      flags bitfield; bit 0 = payload is deflate-compressed, bits 1-7 reserved
//	bytes 3..   nonce||sealed of the payload, authenticated over bytes 0 to 2 and any [WithAAD] data
//
// The header is authenticated, so flipping a flag bit or relabelling the key id of a stored value makes
// [Keyring.Decrypt] fail rather than return a different plaintext. Data bound with [WithAAD] follows the
// header, which has a fixed length, so a value sealed without it authenticates over exactly the three bytes.
//
// Version 0 is permanently reserved and never emitted, so that an application migrating existing plaintext to
// encryption can use a leading zero byte as its own marker for a value it has not sealed yet and tell the two
// apart on read. [Keyring.Decrypt] rejects it with [ErrReservedVersion], and no future version will claim it.
//
// A reader rejects every format version and every flag bit it does not know, which fails closed rather than
// guessing at a value it cannot interpret. New format features therefore deploy in two steps: the version that
// understands a new flag bit or format version has to reach every reader before any writer emits it, or a
// rolling deploy leaves the instances that are still on the old version failing on values the new ones wrote.
package crypto
