// Package crypto seals secrets at rest with AES-256-GCM.
//
// The configured key is hashed to a fixed 32-byte key, so a key of any non-empty length is accepted.
// Ciphertext is stored as nonce||sealed.
//
// The key is derived with a plain SHA-256 hash, which is a fast, unsalted digest rather than a password based
// key derivation function. It is therefore only suitable for keys that already have full entropy, such as
// randomly generated bytes. Do not pass a human chosen password directly, derive a key with a memory hard
// function like Argon2id or scrypt first.
package crypto
