package crypto

import (
	"bytes"
	"compress/flate"
	"crypto/hkdf"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"slices"
	"strconv"
	"strings"
)

// FormatVersion is the first byte of every value a [Keyring] produces, see the package documentation for the
// envelope it introduces. Version 0 is permanently reserved and never emitted, so that an application
// migrating to encryption can use a leading zero byte as its own marker for a value it has not sealed yet.
const FormatVersion byte = 1

// reservedVersion is the version byte that never identifies an envelope. See [FormatVersion].
const reservedVersion byte = 0

// headerLen is the length of the envelope header, which doubles as the additional authenticated data.
const headerLen = 3

// flagCompressed marks a deflated payload. Bits 1 to 7 of the flags byte are reserved and must be zero.
const flagCompressed byte = 1 << 0

// The info strings that expand a configured key into two independent subkeys, so that the AES key and the MAC
// key are never the same bytes. They are part of the stored format: changing one invalidates written values.
const (
	encryptInfo = "glasskube/pkg/crypto:encrypt"
	macInfo     = "glasskube/pkg/crypto:hmac"
)

// MinKeyLen is the shortest key a [Keyring] accepts. Subkeys are derived with HKDF rather than a password based
// KDF, so a key has to carry full entropy by itself: use randomly generated bytes. [New] does not enforce this
// and takes a key of any non-empty length.
const MinKeyLen = 32

// compressThreshold is the payload size below which [WithCompression] does not compress. It is a floor rather
// than a tunable: a small payload has little to gain, while the size of the value it is stored as gives away
// proportionally more about it, so attempting compression below this is a bad trade in both directions.
const compressThreshold = 512

// subkeyLen is the length of both subkeys HKDF expands a configured key into.
const subkeyLen = 32

// Errors reported by [ParseKeyring] for a malformed spec.
var (
	// ErrNoKeys is returned if the spec is empty or holds no usable entry.
	ErrNoKeys = errors.New("no encryption key configured")
	// ErrDuplicateKeyID is returned if two entries share a key id.
	ErrDuplicateKeyID = errors.New("duplicate encryption key id")
	// ErrInvalidKeyID is returned for an id that is not a number or that falls outside 0-255.
	ErrInvalidKeyID = errors.New("invalid encryption key id")
	// ErrInvalidKey is returned for a key that is not valid standard encoding base64.
	ErrInvalidKey = errors.New("invalid encryption key")
	// ErrKeyTooShort is returned for a key that decodes to fewer than [MinKeyLen] bytes.
	ErrKeyTooShort = fmt.Errorf("encryption key must be at least %d bytes", MinKeyLen)
)

// Errors reported by [Keyring.Decrypt] for a value it cannot open.
var (
	// ErrReservedVersion is returned for a value whose version byte is the reserved 0. See [FormatVersion].
	ErrReservedVersion = errors.New("encrypted value uses the reserved format version 0")
	// ErrUnknownVersion is returned for a value whose version byte this code does not know.
	ErrUnknownVersion = errors.New("unrecognized encrypted value format version")
	// ErrUnknownFlag is returned for a value with a flag bit set that this code does not recognize.
	ErrUnknownFlag = errors.New("unrecognized encrypted value flag")
	// ErrUnknownKeyID is returned for a value sealed with a key the keyring is not configured with.
	ErrUnknownKeyID = errors.New("encrypted value was sealed with an unconfigured key")
	// ErrValueTooShort is returned for a value too short to hold an envelope header.
	ErrValueTooShort = errors.New("encrypted value too short")
)

// keyEntry is a configured key and the two subkeys it was expanded into.
type keyEntry struct {
	enc *Encryptor
	mac []byte
	id  byte
}

// Keyring holds every key an application is configured with. The active key seals all writes, the others keep
// values written before a key rotation readable while their key remains configured.
// The zero value is not usable, use [ParseKeyring] to obtain a Keyring.
// A Keyring is safe for concurrent use by multiple goroutines.
type Keyring struct {
	active *keyEntry
	byID   map[byte]*keyEntry
	ids    []byte
}

// ParseKeyring reads a comma separated list of "<id>:<base64 key>" entries, the first of which is the active
// key. Whitespace is trimmed and empty entries are skipped, so a trailing comma is tolerated. A single entry
// may omit the "<id>:" prefix, which then means id 0. Keys are standard base64 of at least [MinKeyLen] bytes.
func ParseKeyring(spec string) (*Keyring, error) {
	entries := strings.Split(spec, ",")
	keyring := Keyring{byID: make(map[byte]*keyEntry, len(entries))}
	for _, entry := range entries {
		if strings.TrimSpace(entry) == "" {
			continue
		}
		k, err := parseKey(entry)
		if err != nil {
			return nil, err
		}
		if _, ok := keyring.byID[k.id]; ok {
			return nil, fmt.Errorf("%w: %d", ErrDuplicateKeyID, k.id)
		}
		keyring.byID[k.id] = k
		keyring.ids = append(keyring.ids, k.id)
		if keyring.active == nil {
			keyring.active = k
		}
	}
	if keyring.active == nil {
		return nil, ErrNoKeys
	}
	return &keyring, nil
}

// parseKey reads a single "<id>:<base64 key>" entry of a keyring spec.
func parseKey(entry string) (*keyEntry, error) {
	id := 0
	encoded := strings.TrimSpace(entry)
	if idPart, keyPart, ok := strings.Cut(encoded, ":"); ok {
		parsed, err := strconv.Atoi(strings.TrimSpace(idPart))
		if err != nil {
			return nil, fmt.Errorf("%w %q: %w", ErrInvalidKeyID, strings.TrimSpace(idPart), err)
		}
		if parsed < 0 || parsed > 255 {
			return nil, fmt.Errorf("%w: %d is out of range 0-255", ErrInvalidKeyID, parsed)
		}
		id = parsed
		encoded = strings.TrimSpace(keyPart)
	}
	if encoded == "" {
		return nil, fmt.Errorf("%w: id %d has no key", ErrInvalidKey, id)
	}
	secret, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("%w with id %d: %w", ErrInvalidKey, id, err)
	}
	if len(secret) < MinKeyLen {
		return nil, fmt.Errorf("%w (id %d has %d)", ErrKeyTooShort, id, len(secret))
	}
	return newKey(byte(id), secret)
}

// newKey expands secret into the encrypt and mac subkeys of the key with the given id.
func newKey(id byte, secret []byte) (*keyEntry, error) {
	encKey, err := hkdf.Key(sha256.New, secret, nil, encryptInfo, subkeyLen)
	if err != nil {
		return nil, fmt.Errorf("derive encryption subkey: %w", err)
	}
	macKey, err := hkdf.Key(sha256.New, secret, nil, macInfo, subkeyLen)
	if err != nil {
		return nil, fmt.Errorf("derive mac subkey: %w", err)
	}
	encryptor, err := New(encKey)
	if err != nil {
		return nil, err
	}
	return &keyEntry{id: id, enc: encryptor, mac: macKey}, nil
}

// ActiveKeyID is the id of the key that [Keyring.Encrypt] and [Keyring.HMAC] use.
func (k *Keyring) ActiveKeyID() byte { return k.active.id }

// KeyIDs are the ids of every configured key, the active one first.
func (k *Keyring) KeyIDs() []byte { return slices.Clone(k.ids) }

// EncryptOption configures a single [Keyring.Encrypt] call.
type EncryptOption func(*encryptOptions)

type encryptOptions struct {
	aad      []byte
	compress bool
}

// WithAAD binds the value to additional authenticated data that [Keyring.DecryptWithAAD] has to be given again
// to open it. Use it to tie a value to where it is stored, such as a column and a row id, so that a value
// copied to another row or column fails to decrypt. The data is authenticated rather than stored, so it has to
// be reconstructible on read and must not change for as long as the value lives.
func WithAAD(aad []byte) EncryptOption {
	return func(o *encryptOptions) { o.aad = aad }
}

// WithCompression attempts to deflate the plaintext before encrypting it. It is off by default because the
// size of a stored value then leaks the length and the compressibility of the plaintext, which is the side
// channel CRIME and BREACH exploit. Enable it where that is an acceptable trade, such as for large values in a
// PostgreSQL column that can no longer be TOAST-compressed once it holds ciphertext.
// Compression is best effort: a payload that does not shrink is sealed as it is.
func WithCompression() EncryptOption {
	return func(o *encryptOptions) { o.compress = true }
}

// Encrypt seals plaintext with the active key and returns the envelope described in the package documentation.
// The header, and anything [WithAAD] binds, are authenticated, so a value whose version, key id or flags were
// modified fails to open. Every call draws a fresh nonce, so sealing the same plaintext twice differs.
func (k *Keyring) Encrypt(plaintext []byte, opts ...EncryptOption) ([]byte, error) {
	var options encryptOptions
	for _, opt := range opts {
		opt(&options)
	}

	flags := byte(0)
	payload := plaintext
	if options.compress {
		if compressed, ok := deflate(plaintext); ok {
			flags |= flagCompressed
			payload = compressed
		}
	}

	// The ciphertext is sealed onto the header, so that a large payload is not copied again to prefix it.
	header := []byte{FormatVersion, k.active.id, flags}
	return k.active.enc.sealAppend(header, payload, envelopeAAD(header, options.aad))
}

// envelopeAAD is the additional authenticated data of a value: its header, followed by whatever [WithAAD] bound
// to it. The header has a fixed length, so concatenating the two is unambiguous, and a value sealed without an
// aad authenticates over exactly the header.
func envelopeAAD(header, aad []byte) []byte {
	if len(aad) == 0 {
		return header
	}
	return slices.Concat(header, aad)
}

// Decrypt opens a value that [Keyring.Encrypt] sealed without [WithAAD].
func (k *Keyring) Decrypt(value []byte) ([]byte, error) {
	return k.DecryptWithAAD(value, nil)
}

// DecryptWithAAD opens a value produced by [Keyring.Encrypt] with the key its header names and returns the
// plaintext, which never aliases value. It fails if that key is not configured, if the value has been tampered
// with, if its header names a format version or a flag this code does not know, or if aad is not what
// [WithAAD] bound to the value.
//
// A value carries no record of whether it was bound, and a mismatched aad is indistinguishable from a tampered
// value, so a caller that starts binding an existing column has to know which of the two shapes it is reading
// until every value has been re-encrypted.
func (k *Keyring) DecryptWithAAD(value, aad []byte) ([]byte, error) {
	if len(value) == 0 {
		return nil, ErrValueTooShort
	}
	switch value[0] {
	case reservedVersion:
		return nil, ErrReservedVersion
	case FormatVersion:
		// The only version this code knows how to read.
	default:
		return nil, fmt.Errorf("%w: %d", ErrUnknownVersion, value[0])
	}
	if len(value) < headerLen {
		return nil, ErrValueTooShort
	}

	header, sealed := value[:headerLen], value[headerLen:]
	id, flags := header[1], header[2]
	configured, ok := k.byID[id]
	if !ok {
		return nil, fmt.Errorf("%w: %d", ErrUnknownKeyID, id)
	}
	if flags & ^flagCompressed != 0 {
		return nil, fmt.Errorf("%w: %08b", ErrUnknownFlag, flags)
	}

	payload, err := configured.enc.DecryptWithAAD(sealed, envelopeAAD(header, aad))
	if err != nil {
		return nil, err
	}
	if flags&flagCompressed != 0 {
		return inflate(payload)
	}
	return payload, nil
}

// HMAC derives the lookup value of a credential that has to stay searchable, such as an access token, with the
// active key. It is deterministic, so an exact match index finds it, and one way, so the stored digest is of
// no use to someone holding a database dump.
func (k *Keyring) HMAC(value []byte) []byte {
	return macSum(k.active.mac, value)
}

// HMACAll derives the lookup value under every configured key, the active one first, because a lookup has to
// accept any of them: a credential hashed before a rotation must still be found while its key is configured.
// Unlike an encrypted value, a digest cannot be moved to a new key, so retiring a key means reissuing every
// credential that was stored under it.
func (k *Keyring) HMACAll(value []byte) [][]byte {
	all := make([][]byte, 0, len(k.ids))
	for _, id := range k.ids {
		all = append(all, macSum(k.byID[id].mac, value))
	}
	return all
}

// macSum is HMAC-SHA256 of value under the given mac subkey.
func macSum(macKey, value []byte) []byte {
	mac := hmac.New(sha256.New, macKey)
	mac.Write(value)
	return mac.Sum(nil)
}

// deflate compresses plaintext, and reports false if it should be stored as it is because compressing it
// failed or did not shrink it.
func deflate(plaintext []byte) ([]byte, bool) {
	if len(plaintext) < compressThreshold {
		return nil, false
	}
	var buf bytes.Buffer
	w, err := flate.NewWriter(&buf, flate.DefaultCompression)
	if err != nil {
		return nil, false
	}
	if _, err := w.Write(plaintext); err != nil {
		return nil, false
	}
	if err := w.Close(); err != nil {
		return nil, false
	}
	if buf.Len() >= len(plaintext) {
		return nil, false
	}
	return buf.Bytes(), true
}

// inflate decompresses a payload that [deflate] compressed. The payload is authenticated before it gets here,
// so a value that expands out of proportion cannot be crafted without the key.
func inflate(compressed []byte) ([]byte, error) {
	plaintext, err := io.ReadAll(flate.NewReader(bytes.NewReader(compressed)))
	if err != nil {
		return nil, fmt.Errorf("decompress: %w", err)
	}
	return plaintext, nil
}
