name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - crypto
          - seekbuf
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: ${{ matrix.module }}/go.mod
      - name: Test ${{ matrix.module }}
        working-directory: ${{ matrix.module }}
        run: go test ./...
      - name: Lint ${{ matrix.module }}
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: "v2.12.2" # renovate: datasource=github-releases depName=golangci/golangci-lint
          working-directory: ${{ matrix.module }}
